
### Get all users
GET http://localhost:3000/api/v1/users

### Get user by id
GET http://localhost:3000/api/v1/users/1


### Create new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "pepe2"
}

### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "pepe2"
}

### Auth me
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImFkZHJlc3MiOm51bGwsImF2YXRhciI6ImRlZmF1bHQuc3ZnIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTM5NjYxOTgsImV4cCI6MTcxNDA1MjU5OH0.lEf7aZO43ZlMnx83FPIUf6jldtI5kxV7LKwI1qkFIJo


### Get avarar by id
GET http://localhost:3000/api/v1/users/avatar/13


### Delete user
DELETE http://localhost:3000/api/v1/users/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsInVzZXJuYW1lIjoicGVwZSIsImVtYWlsIjoiZGFqc2lkamFza0BhZGtqc2thLmNvbW0iLCJhZGRyZXNzIjoiMCIsImF2YXRhciI6bnVsbCwiaWF0IjoxNzEzNDI2MDM1LCJleHAiOjE3MTM1MTI0MzV9.3EBYAjQxMcBNEa89ui4iDGSsRCEOGyoCrGzDY8lFjwI



### Update user  KÄYTÄ POSTMASTERII TÄÄ EI NY HALUA TOIMII >:(
PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInVzZXJuYW1lIjoicGVwZSIsImVtYWlsIjoiZGFqc2lkamFza0BhZGtqc2thLmNvbW0iLCJhZGRyZXNzIjoiMCIsImlhdCI6MTcxMzM3MTg5MCwiZXhwIjoxNzEzNDU4MjkwfQ.w_KhEZ3-qxQfnvxCI_YjJoopbbRbyMxISknIEZsgXQ8
Content-Disposition: form-data; name="file"; filename="default.svg"


{
  "username": "new_username",
  "avatar": "./public/default.svg"
}
