
### Get all users
GET http://10.120.32.57/app/api/v1/users

### Get user by id
GET http://10.120.32.57/app/api/v1/users/1


### Create new user
POST http://10.120.32.57/app/api/v1/users
Content-Type: application/json

{
  "email": "dajsidjask@adkjska.comm",
  "password": "pepe2",
  "username": "pepe",
  "name" : "dajsidjask"
}

### Login
POST http://10.120.32.57/app/api/v1/auth/login
Content-Type: application/json

{
  "username": "pepe",
  "password": "pepe2"
}

### Auth me
GET http://10.120.32.57/app/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInVzZXJuYW1lIjoicGVwZSIsImVtYWlsIjoiZGFqc2lkamFza0BhZGtqc2thLmNvbW0iLCJhZGRyZXNzIjoiMCIsImF2YXRhciI6bnVsbCwiaWF0IjoxNzEzMzczNTMzLCJleHAiOjE3MTM0NTk5MzN9.bi_BKhhg9r06LND-tL3SgE4E0Ok1yB_QGnd4DfUxs00


### Get avarar by id
GET http://10.120.32.57/app/api/v1/users/avatar/13


### Delete user
DELETE http://10.120.32.57/app/api/v1/users/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInVzZXJuYW1lIjoicGVwZSIsImVtYWlsIjoiZGFqc2lkamFza0BhZGtqc2thLmNvbW0iLCJhZGRyZXNzIjoiMCIsImlhdCI6MTcxMzM3MTg5MCwiZXhwIjoxNzEzNDU4MjkwfQ.w_KhEZ3-qxQfnvxCI_YjJoopbbRbyMxISknIEZsgXQ8




### Update user  KÄYTÄ POSTMASTERII TÄÄ EI NY HALUA TOIMII >:(
PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInVzZXJuYW1lIjoicGVwZSIsImVtYWlsIjoiZGFqc2lkamFza0BhZGtqc2thLmNvbW0iLCJhZGRyZXNzIjoiMCIsImlhdCI6MTcxMzM3MTg5MCwiZXhwIjoxNzEzNDU4MjkwfQ.w_KhEZ3-qxQfnvxCI_YjJoopbbRbyMxISknIEZsgXQ8
Content-Disposition: form-data; name="file"; filename="default.svg"


{
  "username": "new_username",
  "avatar": "./public/default.svg"
}
